//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLAP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class managmentEntities : DbContext
    {
        public managmentEntities()
            : base("name=managmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Водители> Водители { get; set; }
        public DbSet<ЗаказаноТоваров> ЗаказаноТоваров { get; set; }
        public DbSet<Заказы> Заказы { get; set; }
        public DbSet<Клиенты> Клиенты { get; set; }
        public DbSet<СкладТоваров> СкладТоваров { get; set; }
        public DbSet<СостояниеЗаказа> СостояниеЗаказа { get; set; }
        public DbSet<ТранспортноеСредство> ТранспортноеСредство { get; set; }
    }
}
