//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказаноТоваров
    {
        public int ЗаказID { get; set; }
        public int КодТовара { get; set; }
        public decimal РасценкаТоннЗаКм { get; set; }
        public int Количество { get; set; }
        public int Масса { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual СкладТоваров СкладТоваров { get; set; }
    }
}
