//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        public Клиенты()
        {
            this.Заказы = new HashSet<Заказы>();
        }
    
        public int КлиентID { get; set; }
        public string ФИО { get; set; }
        public string Адрес { get; set; }
        public string Телефон { get; set; }
    
        public virtual ICollection<Заказы> Заказы { get; set; }
    }
}
