//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLAP.Model_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataBases
    {
        public DataBases()
        {
            this.Dimensions = new HashSet<Dimensions>();
            this.Facts = new HashSet<Facts>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
    
        public virtual ICollection<Dimensions> Dimensions { get; set; }
        public virtual ICollection<Facts> Facts { get; set; }
    }
}
