//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLAP.Model_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measures
    {
        public int Id { get; set; }
        public int DimensionId { get; set; }
        public string ColumnName { get; set; }
        public string Name { get; set; }
        public int Priority { get; set; }
    
        public virtual Dimensions Dimensions { get; set; }
    }
}
