//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLAP.Model_test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OLAPDBmdfEntities : DbContext
    {
        public OLAPDBmdfEntities()
            : base("name=OLAPDBmdfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DataBases> DataBases { get; set; }
        public DbSet<Dimensions> Dimensions { get; set; }
        public DbSet<Measures> Measures { get; set; }
        public DbSet<Facts> Facts { get; set; }
    }
}
